# Done to increase the memory available to gradle
org.gradle.jvmargs=-Xmx3G
# Enable Gradle configuration cache
org.gradle.configuration-cache=true
# enable the remote build cache
org.gradle.caching=true

# Metadata
mod_id=bolt
mod_description=A Minecraft implementation of JoltPhysics
mod_display_name=Bolt
sources_url=https://github.com/CammiePone/Bolt
issues_url=https://github.com/CammiePone/Bolt/issues
license_url=https://github.com/CammiePone/Bolt/blob/HEAD/LICENSE.md
discord_url=https://cammiescorner.dev/discord
homepage_url=https://github.com/CammiePone/Bolt

# Publishing
maven_group_id=dev.cammiescorner.bolt
curseforge_id=0
modrinth_id=0
